### PR TITLE
To redux

### PR DESCRIPTION
**Pull request by TJTorola**
Moves the entire project over to redux. Fixes the following issues in the process, #17, #16, and #15

### CODE REVIEW

**Comment by TJTorola** [comment]
@composerinteralia Please confirm that the following code is sufficient for the NY check in process. The entry.js for reading from the deskHash, and the options view.jsx for storing the desk hash whenever any of the inputs are modified. Thanks.

entry.js
```
const insertDeskHash = () => {
	chrome.storage.local.get("deskHash", storage => {
		$("input.desk-hash").val(storage.deskHash);
	});
};

document.addEventListener("DOMContentLoaded", () => {
	insertDeskHash();
	ReactDom.render(<Root />, document.querySelector('#app'));
});
```

options\form\view.jsx
```
const setDeskHash = e => {
	if (e !== undefined) {
		localStorage["password"] = e.target.value;
	}

	const deskRecipe = ["cityId", "desk", "password"]
		.map(key => localStorage[key])
		.reduce((a, b) => a + b);

	const deskHash = sjcl.codec.hex.fromBits(sjcl.hash.sha256.hash(deskRecipe));
	chrome.storage.local.set({ deskHash });
}

const dispatchChange = dispatch => e => {
	dispatch(e.target.value);
	setDeskHash();
}
```

note: The password input field calls setDeskHash directly with an event onChange, every other input calls it indirectly without an event through dispatchChange.

**Comment by composerinteralia** [comment]
This won't quite work. The content scripts don't get run until after the DOM loads, so the DOMContentLoaded callback will never get called.  Moving insertDeskHash(); up a line should work for now. Could you leave the smiley face in as well; it let's us know at a glance that everything is working.

**Comment by composerinteralia** [comment]
This may be a separate issue, but can you replace the links to backbone docs with links to react docs?

**Comment by TJTorola** [comment]
Here you go @composerinteralia, I replaced the backbone link with redux because react was already in there, and I modified the entry to be as follows.

```
const smile = () => {
  const $html = $("<b>:)</b>");

  $html.css({
    "display": "block",
    "position": "fixed",
    "font-size": "13px",
    "bottom": "5px",
    "right": "5px",
    "-webkit-transform": "rotate(90deg)",
    "font-family": "Inconsolata, monospace"
  });

  $("body").append($html);
};

const insertDeskHash = () => {
	chrome.storage.local.get("deskHash", storage => {
		$("input.desk-hash").val(storage.deskHash);
		smile();
	});
};

document.addEventListener("DOMContentLoaded", () => {
	ReactDom.render(<Root />, document.querySelector('#app'));
	insertDeskHash();
});
```

Question, where is the desk-hash input actually? I can't find it in this or the old versions of the chrome-extension.

**Comment by composerinteralia** [comment]
Sorry if I didn't make that clear when we first chatted. The desk-hash input is on the progress tracker. NYC students see a check-in button when they visit progress.appacady.io/me.

The `context_scripts` in `manifest.json` basically allows whatever javascript files are in the `js` array to run when the url matches anything in the `matches` array. They run after the DOM content loads, so the call to `insertDeskHash` will need to be outside of your `DOMContentLoaded` callback.

**Comment by TJTorola** [comment]
Ok thanks for clearing that up, it makes much more sense to me now and I think I got it fixed. I added a check so that the smile confirmation will only show up when the input is found, when going to appacademy.io it did show up with the new extension so I assume that things are good.

```
const insertDeskHash = () => {
	chrome.storage.local.get("deskHash", storage => {
		const $input = $("input.desk-hash")
		if ($input.length) {
			$input.val(storage.deskHash);
			smile();
		}
	});
};

insertDeskHash();

document.addEventListener("DOMContentLoaded", () => {
	ReactDom.render(<Root />, document.querySelector('#app'));
});
```

**Comment by composerinteralia** [comment]
Looks good to me!

**Pull request merged**
